model:
  name: hubert_large
  revision: main
  cache_dir: ./data/cache/huggingface
  apply_spec_augment: false
  max_input_sec: 90
  layerdrop: 0.0
  head_hidden_dim: null
  dropout: 0.1
  gradient_checkpointing: true
