model:
  name: hubert_large
  revision: main
  cache_dir: ./data/cache/huggingface
  apply_spec_augment: false
  layerdrop: 0.0
  head_hidden_dim: null
  dropout: 0.1
  max_total_sec: 90
  gradient_checkpointing: true

